spring:
  datasource:
    url: 
    username: 
    password: 

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: default
  output:
    ansi:
      enabled: always
  application:
    name: app

server:
  port: 8080
  session:
    timeout: 30
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
